- templates/Visua11yPreview.jsx
- templates/Visua11ySettings.jsx
fixes [#12](https://github.com/cgkineo/adapt-visua11y/issues/12)
fixes [#13](https://github.com/cgkineo/adapt-visua11y/issues/13)
fixes [#14](https://github.com/cgkineo/adapt-visua11y/issues/14)
**Changed** 
- Role changed from 'listItems' to 'group'
**Fixed**
- Exclude checkbox labels from screen reader
- Exclude preview from screen reader
**Added**
- Checkbox input aria-labels
> issue/12-14 Various fixes

- less/visua11ySettings.less
Fixes #41 
This PR adds a border to the Readability button selected states.
There were already commented out border styles here, so I've uncommented them.  This should resolve the original a11y issue, but I'm not sure why they were commented out in the first place? @kirsty-hames  Looks like you added those styles?
> #41 Show border on Readability buttons selected state

- less/visua11ySettings.less
fixes #44 
Adds a browser default outline to the Readability options when using the keyboard to navigate.
> #44 Fixes No visual keyboard focus on Readability options

- example.json
- js/Visua11yButtonView.js
- properties.schema
- templates/Visua11ySettings.jsx
This PR ensure a valid label is associated with the accessibility dialog using either aria-label or aria-labelledy with a valid id reference. Currently the notify is referencing the notify-heading which doesn't exist. I've added the notify heading & body to this dialogue so screen readers have that association.
I've additionally removed the 'description' field in favor of the standard notify 'title' & 'body'.
I could use a hand as the visua11y view currently appears BEFORE the notify title & body. It could also use some minor styling as well so the notify heading matches widths with visua11y.
#30
> Issue/#30 - Notify headings adds back screen reader association

- example.json
- js/Visua11yButtonView.js
Fixes #47 
This PR adds an option for `_showCloseButton` that controls whether the close button is shown at the top of the Notify popup.  By default, it will not be shown as is currently the case.
Note that the title/body styles are dependent on PR #46 .  Otherwise, the background area is transparent and too wide.
> #47 Fixes no Close button configuration option

- less/modifiers.less
Both adapt-svg and adapt-graphicLottie provide course content graphics and should be removed when [_noBackgroundImages](https://github.com/cgkineo/adapt-visua11y/blob/db8cfc126f8b01f9c6d72ea34aa73832addcb877/example.json#L60) is enabled if alt text isn't set.
adapt-svg - fixes https://github.com/cgkineo/adapt-svg/issues/18 with https://github.com/cgkineo/adapt-svg/pull/20
adapt-graphicLottie - fixes https://github.com/cgkineo/adapt-graphicLottie/issues/6
> extend no background images support to include Lottie animations

- js/Visua11yButtonView.js
- properties.schema
Fixes https://github.com/cgkineo/adapt-visua11y/issues/53
For consistency with other navigation buttons, Visua11y should support data-order to meet AA accessibility https://github.com/adaptlearning/adapt-contrib-core/pull/61
Unless all navigation buttons support data-order the display order won't be entirely configurable.
> Update: Add data-order to support navigation sorting (fixes #53)

- less/visua11ySettings.less
Fixes: #57 
* Add padding-right override to readability item to widen space available
> Fix: Readability padding right override (fixes #57)

- less/modifiers.less
'no background images' no longer hides Vanilla and Boxmenu background images since the following amends were made to apply the `background-image` to it's own div.
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/334
https://github.com/adaptlearning/adapt-contrib-boxMenu/pull/119
[modifiers.less](https://github.com/cgkineo/adapt-visua11y/blob/e89f13ec784c1a997f9eec8a9646849f3f62cc8e/less/modifiers.less#L69) just needs updating to target the .background element instead.
> Breaking: update theme bg image selector (fixes #59)

- js/adapt-visua11y.js
Append `.a11y-invert` to `html` when 'invert' is enabled. Class can be targeted for any overrides or custom styles required in a theme.
Fixes https://github.com/cgkineo/adapt-visua11y/issues/66
> New: Add html 'a11y-invert' class selector for custom theme styles (fixes #66)

- js/COLOR_NAMES.js
- js/CSSRuleModifiers.js
- js/Color.js
fixes #77 
* Allow 'initial', 'inherit', 'unset', 'revert' and 'revert-layer' to pass-through modification rules
https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value
> Fix: Added keyword support

- js/Visua11yButtonView.js
- properties.schema
Fixes #52 
For consistency with core navigation buttons when tooltips are enabled. Ref: https://github.com/adaptlearning/adapt-contrib-core/pull/207
You need to enable Adapt tooltips in _course.json_:
```
"_tooltips": {
"_isEnabled": true
}
```
And use the following config to enable the Visua11y tooltip in _course.json_ (nesting within `_globals` `_extensions`):
```
"_visua11y": {
"_navTooltip": {
"_isEnabled": true,
"text": "Visual accessibility settings"
}
}
```
Note, we haven't updated an extension to support the tooltip API as of yet so I've based the config for this on how the core nav buttons are currently configured, but happy to take steer on this.
I haven't tested this in the AAT as we're not officially supporting this yet.
> New: Add support for tooltip API (fixes #52)

- js/Visua11yNavigationButtonView.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#96 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* aria-expanded attribute added to navigation button (fixes #96)
> Fix: aria-expanded attribute added to navigation button (#96)

- js/ColorTransformations.js
fixes #99
If `_highContrastLuminanceThreshold` is defined as a string `"70"` in the json, rather than a number `70`, the high contrast calculations will not be applied properly, converting all bright colours to 30% darkness.
* Converts `_highContrastLuminanceThreshold` to a number
> Fix: _highContrastLuminanceThreshold as string (fixes #99)

- less/preview.less
- less/visua11ySettings.less
Fixes #105 
* Updated RTL styling to remove unnecessary declarations
> Update: Updated RTL styling (fixes #105)

- properties.schema
- schema/course.schema.json
Fixes https://github.com/cgkineo/adapt-visua11y/issues/107
* Set `title` as `required`. Without a title, the popup `dialog` won't be properly identified by assistive technologies.
> Fix: Title is required to set notify popup dialog label (fixes #107)

- less/buttons.less
Fixes https://github.com/cgkineo/adapt-visua11y/issues/111
The nav button [float](https://github.com/cgkineo/adapt-visua11y/blob/f952a6516e1ecaa2ad1ccdea544d3cd6a4299469/less/buttons.less#L2) style is no longer required since the plugin was updated to support [`data-order`](https://github.com/cgkineo/adapt-visua11y/pull/93).
Core also [overrides](https://github.com/adaptlearning/adapt-contrib-core/blob/8b36e3ee68941b62e711198f49fa9345c1758132/less/core/nav.less#L38) any `.nav__btn` `float` styles.
> Update: remove legacy nav btn float (fixes #111)

- README.md
- bower.json
- js/CSSRuleModifiers.js
- less/buttons.less
- package.json
Fixes https://github.com/cgkineo/adapt-visua11y/issues/73
* When 'No Transparency' is enabled, remove `box-shadow` styles containing transparency. Meaning, where `box-shadow` has an offset and/or blur value, to create a drop shadow effect for example. A zero offset and blur displays as a solid border (no transparency) so there's no reason to remove this. Quite often `box-shadow` is used in favour of `border` or `outline` as it offers more flexibility styling.
* When 'No Transparency' enabled, remove `text-shadow` styles.
1. Install Visua11y. Copy the [example](https://github.com/cgkineo/adapt-visua11y/blob/98bbb4f381afcc02eb0101e0799fa129a4810866/example.json#L13) config into _course.json_ and enable.
2. Add some `box-shadow` and `text-shadow` styles to your theme. For example:
``` …
```
> Update: remove text-shadow + box-shadow when 'No Transparency' enabled (fixes #73)

- templates/Visua11ySettings.jsx
Fixes #121 
* Add `aria-hidden` to label
* Add `aria-label` to `<select>` element 
* Added a11y import
> Fix: Double colour profile read fix (fixes #121)

- js/Visua11yNavigationButtonView.js
Fixes https://github.com/cgkineo/adapt-visua11y/issues/129
The navigation button that triggers a dialog to open (Drawer or Notify), the button `aria-expanded` has been replaced with `aria-haspopup="dialog"`.  Please refer to the [issue](https://github.com/adaptlearning/adapt-contrib-core/issues/657) for the research and discussion supporting this change.
Navigate to the Visua11y button in the nav bar using a screen reader. Depending on the browser/screen reader used, expect the following reading....
VoiceOver “Visual accessibility settings, dialog pop-up, button”
NVDA “Visual accessibility settings, button opens dialog”
JAWS “Visual accessibility settings, button has popup dialog”
Tested with the following combinations:
VoiceOver Safari macOS and iPhone
VoiceOver Chrome and Firefox macOS …
> Update: Replace dialog button aria-expanded with aria-haspopup dialog (fixes #129)

- README.md
- less/modifiers.less
- less/normalise.less
- package.json
Update #128 
* Update <html> target selector from element `html` to class `.html`
* Bumps required FW version to [5.46.4](https://github.com/adaptlearning/adapt_framework/releases/tag/v5.46.4) for Core [6.60.13](https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.60.13) dependency
* Remove IE 11 references from Less and _README.md_
* Update _README.md_ for markdownlint issues
> Update: Update html target selector from element to class (fix #128)
